### ISSUE TITLE
Add ability to customize theme color?

### ISSUE THREAD

**Issue by sutibun** [backdrop-contrib/cleanish#4]
I would like to at least be able to customize the black navigation bar to something else so it won't look exactly like other sites. Possible?

**Comment by docwilmot** [comment]
Hi @sutibun,
You mean a UI for this like a theme settings page? I suppose in the future we could add color module support to the theme rather than just a UI for the menu color. 

But I dont think i can manage that now, I'm working on other Backdrop and multiple other non-Backdrop stuff right now. If it becomes a strong requirement for you (or if other users ask for it) please let me know I'll give it a shot ASAP.

Meanwhile the menu can be altered via custom CSS.

**Comment by sutibun** [comment]
Yes, a UI setting. I've seen them in past Drupal themes. But no no no... it's not urgent. At least, not for me.

I forgot about using CSS. It's just I haven't done theming in Drupal/Bd. [Looks very involved](https://api.backdropcms.org/themes)

Can I modify style.css directly found under /themes/cleanish?

**Comment by docwilmot** [comment]
> Can I modify style.css directly found under /themes/cleanish?

Yes you can but we dont recommend that because if you then do an automatic upgrade (like through the UI), all your changes would be wiped. So make a subtheme. Its not too hard. The same link explains how. Essentially:
- Create a new folder under `/themes`. Name it `subclean`.
- In it put a `subclean.css,` and a `subclean.info` with the following in it:

```
name = Sub Clean
description = This is a sub-theme of Cleanish.
backdrop = 1.x
type = theme
base theme = cleanish
stylesheets[all][]   = subclean.css
```

Flush caches, and enable your new theme. Make all your CSS changes in `subclean.css`.

**Comment by sutibun** [comment]
Ah ok, will try that. Thanks @docwilmot
